//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examen23v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tavar
    {
        public int ID { get; set; }
        public string Производитель { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string Наименование { get; set; }
        public string Изображение { get; set; }
        public string Активен { get; set; }
    }
}
